account_id = "f03ac6f7f9be6238eabb9d9d2097cec8"
name = "puzzle-dev"
type = "webpack"
zone_id = "c8bf4d84a7912cd966204bb83946d7fd"
workers_dev = true
compatibility_date = "2022-03-16"

[build]
command = "yarn && yarn build"

[build.upload]
format = "service-worker"

[site]
bucket = "./dist"
entry-point = "../../workers-site"

[env.staging]
name = "puzzle-staging"
workers_dev = false
route = "https://puzzlestaging.alemoretto.it/*"

[env.production]
name = "puzzle"
workers_dev = false
route = "https://puzzle.alemoretto.it/*"

